[package]
name = "key-logger"
version = "0.1.0"
authors = ["Brian Myers <brian.carl.myers@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
actix-web = "1.0.0-alpha.6"
crossbeam = "0.7"
failure = "0.1"
structopt = "0.2"

[build-dependencies]
bindgen = "0.49"
pkg-config = "0.3"
